fix: DevContainerでLaTeX Workshopを用いた開発を出来るようにした
syoch/LaTeX-Pub pull request #1
Opened 2024-12-14 15:41 UTC by yukikamome316

## What's changed
- `wk-j.save-and-run` の代わりに LaTeX Workshop のビルド構成を用いて同様の機能を実現した
- LaTeX Workshop のプレビュー機能で変更内容をすぐに確認できるようにした
- README を追加した

2024-12-14 16:06 UTC, syoch requested changes
SaveAndRun との併用で drawio 等のリソースの変更時にもビルドを回してほしい．

2024-12-14 16:13 UTC, yukikamome316 commented
以下の拡張機能で実現できそう
https://qiita.com/annin401/items/ae53347608a95f049c9f

2024-12-15 03:38 UTC, yukikamome316 commented
@syoch 
ついでに、これって`make -j`できるのかな？

2024-12-15 03:44 UTC, syoch commented
おそらく可能
並列化するならリソースのビルドだけに限定したほうがいいがしれない（make - j 12 copy_res → make のように）

aux ファイルに変化がなくなるまで uplatex を実行するからその辺で変な挙動しそう

2024-12-15 05:59 UTC, yukikamome316 commented
@syoch 

> おそらく可能 並列化するならリソースのビルドだけに限定したほうがいいがしれない（make - j 12 copy_res → make のように）
> 
> aux ファイルに変化がなくなるまで uplatex を実行するからその辺で変な挙動しそう

うーん、あんまり効果得られなさそうだな
とりあえず drawio と、ついでに CSV の自動ビルドを組んだのでレビューお願い！

2024-12-16 13:18 UTC, syoch commented
よさそう
マージします

2024-12-16 13:18 UTC, merged